### PR TITLE
Task finished

### PR DESCRIPTION
**Pull request by alv-c**
The Task-5 is finished now.
I changed the code, maybe a bit too much. question::display() method was split into two. 
The default question::display() that shows the question with it points, correct answer and possible answers.

And question::display_possible_answers() that shows only possible answers to this question.
This method is used in student::take() so we don't need to compare again the type of question and that.

Also, of course, added the student class.

### CODE REVIEW

**Comment by guitarxhero** [comment]
Nice, thanks!

**Comment by guitarxhero** [comment]
Just forgot to change the [0-2] but hey gg

**Comment by alv-c** [comment]
oh yeah, sorry about that

**Comment by guitarxhero** [comment]
fixed with 348493d   npnpthxu

**Pull request merged**
